### ISSUE TITLE
Develop new girder plugin that depends on Minerva plugin for resource management

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/nex#18]
- [x] UI for resource paner
- [x] UI to configure instances
- [x] UI to start / stop

**Comment by aashish24** [comment]
@kotfic can you refer to culumus issues here?

**Comment by kotfic** [comment]
@aashish24 most of those issues are server side and won't effect the API that this client side plugin works with.  They are not blockers - or really even related to the client side plugin.
