### ISSUE TITLE
Add example that calculates mean for a particular parameter over a set of timesteps

### ISSUE THREAD

**Issue by cjh1** [OpenGeoscience/nex#2]
For example calculating daily mean.

**Comment by aashish24** [comment]
+1

**Comment by aashish24** [comment]
a day would be really good, if you don'thave enough timestramps > 2 then use month

**Comment by cjh1** [comment]
The dataset I am looking at is monthly, but I can provide the ability todo
it over n timesteps.

On Wed, Apr 22, 2015 at 1:55 PM, Aashish Chaudhary <notifications@github.com

**Comment by aashish24** [comment]
sure.. then you can do yearly averages.. for example

**Comment by cjh1** [comment]
Spark version is pretty much done. Now need to write a serial version to do a comparison.
