### ISSUE TITLE
Fix timestamp in ETL for GDDP dataset

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/nex#25]

**Comment by kotfic** [comment]
Turns out sparkSQL has very easy built in functions to deal with unix timestamps,  so this is not really necessary.

**Comment by aashish24** [comment]
This is great to know. Can you post an example here?

**Comment by kotfic** [comment]
``` python
sql = """
SELECT lat, lon, time, model, pr, tasmin, tasmax, MONTH(from_unixtime(time)) as month, YEAR(from_unixtime(time)) as year
FROM parquet
WHERE pr < 1.0E20 AND tasmin < 1.0E20 AND tasmax < 1.0E20
"""
df = sqlContext.sql(sql)
```

`time` is a column containing unix timestamps,  we use the `from_unixtime()` builtin function and the `MONTH()` built in function to pull values from the timestamp
